In [18]:
import pandas as pd

url = "https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/data/deputat.csv"
df = pd.read_csv(url)
df

,name,lastname,otchestvo,gender,birthdate,start,end,district
0,Ефимов,Виталий,Борисович,м,04.04.1940,18.09.2016,NaN,Мордовский
1,Максимова,Надежда,Сергеевна,ж,13.01.1942,18.09.2016,NaN,Хакасский
2,Мищеряков,Юрий,Николаевич,м,01.01.1945,18.09.2016,NaN,Оренбургский
3,Борцов,Николай,Иванович,м,08.09.1945,18.09.2016,NaN,Липецкий
4,Гончар,Николай,Николаевич,м,18.10.1946,18.09.2016,NaN,Центральный
...,...,...,...,...,...,...,...,...
206,Федяев,Павел,Михайлович,м,31.07.1982,18.09.2016,NaN,Заводский
207,Романов,Михаил,Валентинович,м,03.11.1984,18.09.2016,NaN,Юго-Восточный
208,Грибов,Александр,Сергеевич,м,22.05.1986,18.09.2016,NaN,Ярославский
209,Прокопьев,Александр,Сергеевич,м,05.08.1986,18.09.2016,NaN,Бийский
210,Шипулин,Антон,Владимирович,м,21.08.1987,08.09.2019,NaN,Серовский

In [19]:
import datetime
from datetime import datetime, timedelta

def convert_to_datetime(row):
    return datetime.strptime(row['birthdate'], '%d.%m.%Y')

In [20]:
df['birthdate']=df.apply(convert_to_datetime, axis=1)

In [22]:
import time
def make_unix_time(row):
    return time.mktime(row['birthdate'].timetuple())

In [33]:
df['Возраст']=list(map(lambda x: 2020-x.year,df['birthdate']))

In [35]:
df['Возраст'].mean()

56.2654028436019