In [1]:
import requests  
response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')

In [2]:
currencies = response.json()
currencies

{'Date': '2020-06-12T11:30:00+03:00',
 'PreviousDate': '2020-06-11T11:30:00+03:00',
 'PreviousURL': '//www.cbr-xml-daily.ru/archive/2020/06/11/daily_json.js',
 'Timestamp': '2020-06-11T22:00:00+03:00',
 'Valute': {'AUD': {'ID': 'R01010',
   'NumCode': '036',
   'CharCode': 'AUD',
   'Nominal': 1,
   'Name': 'Австралийский доллар',
   'Value': 47.9706,
   'Previous': 48.0191},
  'AZN': {'ID': 'R01020A',
   'NumCode': '944',
   'CharCode': 'AZN',
   'Nominal': 1,
   'Name': 'Азербайджанский манат',
   'Value': 40.7438,
   'Previous': 40.447},
  'GBP': {'ID': 'R01035',
   'NumCode': '826',
   'CharCode': 'GBP',
   'Nominal': 1,
   'Name': 'Фунт стерлингов Соединенного королевства',
   'Value': 87.6673,
   'Previous': 87.6462},
  'AMD': {'ID': 'R01060',
   'NumCode': '051',
   'CharCode': 'AMD',
   'Nominal': 100,
   'Name': 'Армянских драмов',
   'Value': 14.305,
   'Previous': 14.2037},
  'BYN': {'ID': 'R01090B',
   'NumCode': '933',
   'CharCode': 'BYN',
   'Nominal': 1,
   'Name': 'Белорусский рубль',
   'Value': 29.1248,
   'Previous': 28.9504},
  'BGN': {'ID': 'R01100',
   'NumCode': '975',
   'CharCode': 'BGN',
   'Nominal': 1,
   'Name': 'Болгарский лев',
   'Value': 40.1895,
   'Previous': 39.8944},
  'BRL': {'ID': 'R01115',
   'NumCode': '986',
   'CharCode': 'BRL',
   'Nominal': 1,
   'Name': 'Бразильский реал',
   'Value': 13.8966,
   'Previous': 14.0034},
  'HUF': {'ID': 'R01135',
   'NumCode': '348',
   'CharCode': 'HUF',
   'Nominal': 100,
   'Name': 'Венгерских форинтов',
   'Value': 22.8234,
   'Previous': 22.6894},
  'HKD': {'ID': 'R01200',
   'NumCode': '344',
   'CharCode': 'HKD',
   'Nominal': 10,
   'Name': 'Гонконгских долларов',
   'Value': 89.1826,
   'Previous': 88.5375},
  'DKK': {'ID': 'R01215',
   'NumCode': '208',
   'CharCode': 'DKK',
   'Nominal': 1,
   'Name': 'Датская крона',
   'Value': 10.5439,
   'Previous': 10.4665},
  'USD': {'ID': 'R01235',
   'NumCode': '840',
   'CharCode': 'USD',
   'Nominal': 1,
   'Name': 'Доллар США',
   'Value': 69.1219,
   'Previous': 68.6183},
  'EUR': {'ID': 'R01239',
   'NumCode': '978',
   'CharCode': 'EUR',
   'Nominal': 1,
   'Name': 'Евро',
   'Value': 78.5225,
   'Previous': 77.9229},
  'INR': {'ID': 'R01270',
   'NumCode': '356',
   'CharCode': 'INR',
   'Nominal': 100,
   'Name': 'Индийских рупий',
   'Value': 91.2127,
   'Previous': 90.771},
  'KZT': {'ID': 'R01335',
   'NumCode': '398',
   'CharCode': 'KZT',
   'Nominal': 100,
   'Name': 'Казахстанских тенге',
   'Value': 17.2695,
   'Previous': 17.1565},
  'CAD': {'ID': 'R01350',
   'NumCode': '124',
   'CharCode': 'CAD',
   'Nominal': 1,
   'Name': 'Канадский доллар',
   'Value': 51.304,
   'Previous': 51.2421},
  'KGS': {'ID': 'R01370',
   'NumCode': '417',
   'CharCode': 'KGS',
   'Nominal': 100,
   'Name': 'Киргизских сомов',
   'Value': 92.953,
   'Previous': 92.5657},
  'CNY': {'ID': 'R01375',
   'NumCode': '156',
   'CharCode': 'CNY',
   'Nominal': 10,
   'Name': 'Китайских юаней',
   'Value': 97.7624,
   'Previous': 97.1023},
  'MDL': {'ID': 'R01500',
   'NumCode': '498',
   'CharCode': 'MDL',
   'Nominal': 10,
   'Name': 'Молдавских леев',
   'Value': 40.2574,
   'Previous': 40.0107},
  'NOK': {'ID': 'R01535',
   'NumCode': '578',
   'CharCode': 'NOK',
   'Nominal': 10,
   'Name': 'Норвежских крон',
   'Value': 73.6052,
   'Previous': 74.2638},
  'PLN': {'ID': 'R01565',
   'NumCode': '985',
   'CharCode': 'PLN',
   'Nominal': 1,
   'Name': 'Польский злотый',
   'Value': 17.5784,
   'Previous': 17.5391},
  'RON': {'ID': 'R01585F',
   'NumCode': '946',
   'CharCode': 'RON',
   'Nominal': 1,
   'Name': 'Румынский лей',
   'Value': 16.2537,
   'Previous': 16.1409},
  'XDR': {'ID': 'R01589',
   'NumCode': '960',
   'CharCode': 'XDR',
   'Nominal': 1,
   'Name': 'СДР (специальные права заимствования)',
   'Value': 95.8589,
   'Previous': 94.7708},
  'SGD': {'ID': 'R01625',
   'NumCode': '702',
   'CharCode': 'SGD',
   'Nominal': 1,
   'Name': 'Сингапурский доллар',
   'Value': 49.8032,
   'Previous': 49.5439},
  'TJS': {'ID': 'R01670',
   'NumCode': '972',
   'CharCode': 'TJS',
   'Nominal': 10,
   'Name': 'Таджикских сомони',
   'Value': 67.1902,
   'Previous': 66.6521},
  'TRY': {'ID': 'R01700J',
   'NumCode': '949',
   'CharCode': 'TRY',
   'Nominal': 1,
   'Name': 'Турецкая лира',
   'Value': 10.1981,
   'Previous': 10.1083},
  'TMT': {'ID': 'R01710A',
   'NumCode': '934',
   'CharCode': 'TMT',
   'Nominal': 1,
   'Name': 'Новый туркменский манат',
   'Value': 19.7774,
   'Previous': 19.6333},
  'UZS': {'ID': 'R01717',
   'NumCode': '860',
   'CharCode': 'UZS',
   'Nominal': 10000,
   'Name': 'Узбекских сумов',
   'Value': 68.087,
   'Previous': 67.6242},
  'UAH': {'ID': 'R01720',
   'NumCode': '980',
   'CharCode': 'UAH',
   'Nominal': 10,
   'Name': 'Украинских гривен',
   'Value': 25.9902,
   'Previous': 25.7568},
  'CZK': {'ID': 'R01760',
   'NumCode': '203',
   'CharCode': 'CZK',
   'Nominal': 10,
   'Name': 'Чешских крон',
   'Value': 29.4926,
   'Previous': 29.3435},
  'SEK': {'ID': 'R01770',
   'NumCode': '752',
   'CharCode': 'SEK',
   'Nominal': 10,
   'Name': 'Шведских крон',
   'Value': 75.0126,
   'Previous': 74.768},
  'CHF': {'ID': 'R01775',
   'NumCode': '756',
   'CharCode': 'CHF',
   'Nominal': 1,
   'Name': 'Швейцарский франк',
   'Value': 73.4168,
   'Previous': 72.5045},
  'ZAR': {'ID': 'R01810',
   'NumCode': '710',
   'CharCode': 'ZAR',
   'Nominal': 10,
   'Name': 'Южноафриканских рэндов',
   'Value': 41.5831,
   'Previous': 41.3817},
  'KRW': {'ID': 'R01815',
   'NumCode': '410',
   'CharCode': 'KRW',
   'Nominal': 1000,
   'Name': 'Вон Республики Корея',
   'Value': 57.8615,
   'Previous': 57.708},
  'JPY': {'ID': 'R01820',
   'NumCode': '392',
   'CharCode': 'JPY',
   'Nominal': 100,
   'Name': 'Японских иен',
   'Value': 64.609,
   'Previous': 63.9529}}}

In [3]:
currencies['Valute']['USD']['Value']

69.1219

In [37]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/data/it_new.csv')
df.head(10)

,id,Дата рождения,Вакансия,Технология,Локация,З/п в валюте найма,col,curenc
0,1,18.04.1994,Инженер-программист 2 категории,JS,Санкт-Петербург,"140 000,00 ₽",140000.0,₽
1,2,27.03.1993,Разработчик информационных систем,.NET,Москва,"130 000,00 ₽",130000.0,₽
2,3,24.11.1983,Java Developer,Java,Санкт-Петербург,"200 000,00 ₽",200000.0,₽
3,4,09.06.1989,Архитектор ПО,Java,Москва,"250 000,00 ₽",250000.0,₽
4,5,03.10.1978,QA Automation Engineer,QA,Санкт-Петербург,"172 413,00 ₽",172413.0,₽
5,6,21.08.1973,Big Data Developer,Big Data,Санкт-Петербург,"280 000,00 ₽",280000.0,₽
6,7,10.10.1991,JS Developer,JS,Москва,"129 000,00 ₽",129000.0,₽
7,8,16.08.1982,Разработчик мобильных приложений,Android,Москва,"185 000,00 ₽",185000.0,₽
8,9,16.05.1988,Инженер-программист 2 категории,.NET,Санкт-Петербург,"160 000,00 ₽",160000.0,₽
9,10,01.12.1990,Java Engineer,Java,Краков; Польша,"9 500,00 zł",9500.0,zł

In [5]:
#задание:

In [8]:
df['curenc'].unique()

array(['₽', 'zł', 'Kč', '$', 'lev', 'Ft', '€'], dtype=object)

In [38]:
df['curenc']=df['curenc'].replace({'zł':'PLN', 'Kč':'CZK', '$':'USD', 'lev':'BGN', 'Ft':'HUF', '€':'EUR'})
df.head(10)

,id,Дата рождения,Вакансия,Технология,Локация,З/п в валюте найма,col,curenc
0,1,18.04.1994,Инженер-программист 2 категории,JS,Санкт-Петербург,"140 000,00 ₽",140000.0,₽
1,2,27.03.1993,Разработчик информационных систем,.NET,Москва,"130 000,00 ₽",130000.0,₽
2,3,24.11.1983,Java Developer,Java,Санкт-Петербург,"200 000,00 ₽",200000.0,₽
3,4,09.06.1989,Архитектор ПО,Java,Москва,"250 000,00 ₽",250000.0,₽
4,5,03.10.1978,QA Automation Engineer,QA,Санкт-Петербург,"172 413,00 ₽",172413.0,₽
5,6,21.08.1973,Big Data Developer,Big Data,Санкт-Петербург,"280 000,00 ₽",280000.0,₽
6,7,10.10.1991,JS Developer,JS,Москва,"129 000,00 ₽",129000.0,₽
7,8,16.08.1982,Разработчик мобильных приложений,Android,Москва,"185 000,00 ₽",185000.0,₽
8,9,16.05.1988,Инженер-программист 2 категории,.NET,Санкт-Петербург,"160 000,00 ₽",160000.0,₽
9,10,01.12.1990,Java Engineer,Java,Краков; Польша,"9 500,00 zł",9500.0,PLN

In [39]:
def exchange(row):
    if (row['curenc']!='₽'):
        return "{:.15f}".format(row['col']*currencies['Valute'][row['curenc']]['Value'])
    else:
        return row['col']

In [40]:
df['col']=df.apply(exchange,axis=1)
df

,id,Дата рождения,Вакансия,Технология,Локация,З/п в валюте найма,col,curenc
0,1,18.04.1994,Инженер-программист 2 категории,JS,Санкт-Петербург,"140 000,00 ₽",140000,₽
1,2,27.03.1993,Разработчик информационных систем,.NET,Москва,"130 000,00 ₽",130000,₽
2,3,24.11.1983,Java Developer,Java,Санкт-Петербург,"200 000,00 ₽",200000,₽
3,4,09.06.1989,Архитектор ПО,Java,Москва,"250 000,00 ₽",250000,₽
4,5,03.10.1978,QA Automation Engineer,QA,Санкт-Петербург,"172 413,00 ₽",172413,₽
5,6,21.08.1973,Big Data Developer,Big Data,Санкт-Петербург,"280 000,00 ₽",280000,₽
6,7,10.10.1991,JS Developer,JS,Москва,"129 000,00 ₽",129000,₽
7,8,16.08.1982,Разработчик мобильных приложений,Android,Москва,"185 000,00 ₽",185000,₽
8,9,16.05.1988,Инженер-программист 2 категории,.NET,Санкт-Петербург,"160 000,00 ₽",160000,₽
9,10,01.12.1990,Java Engineer,Java,Краков; Польша,"9 500,00 zł",166994.799999999988358,PLN
10,11,04.02.1991,Инженер-программист,JavaScript,Москва,"170 000,00 ₽",170000,₽
11,12,11.02.1982,.NET Engineer,.NET,Гданьск; Польша,"12 000,00 zł",210940.799999999988358,PLN
12,13,04.11.1988,JavaScript Engineer,JavaScript,Краков; Польша,"10 500,00 zł",184573.199999999982538,PLN
13,14,09.04.1990,Software Engineer,JS,Вроцлав; Польша,"9 500,00 zł",166994.799999999988358,PLN
14,15,16.03.1986,Head of Software Testing Department,QA,Санкт-Петербург,"375 000,00 ₽",375000,₽
15,16,30.08.1982,Java Developer,Java,Москва,"180 000,00 ₽",180000,₽
16,17,05.01.1984,Data / DWH Analyst,DB,Прага; Чехия,"60 000,00 Kč",1769556.000000000000000,CZK
17,18,28.08.1995,JS Developer,JavaScript,Москва,"160 000,00 ₽",160000,₽
18,19,02.02.1972,Senior Software Engineer,BI,Санкт-Петербург,"200 000,00 ₽",200000,₽
19,20,21.09.1985,QA Engineer,QA,Санкт-Петербург,"135 000,00 ₽",135000,₽
20,21,06.07.1990,Разработчик интерфейсов,JavaScript,Санкт-Петербург,"113 000,00 ₽",113000,₽
21,22,13.11.1991,3D Artist,GameDev,Минск,"$2 000,00",138243.799999999988358,USD
22,23,03.02.1970,Senior Tester,QA,Санкт-Петербург,"145 000,00 ₽",145000,₽
23,24,29.10.1987,Инженер-программист,JavaScript,Санкт-Петербург,"190 000,00 ₽",190000,₽
24,25,05.03.1989,Big Data Developer,Scala,Санкт-Петербург,"250 000,00 ₽",250000,₽
25,26,29.12.1991,Разработчик информационных систем,.NET,Москва,"200 000,00 ₽",200000,₽
26,27,01.11.1991,Фронтенд разработчик,JavaScript,Санкт-Петербург,"300 000,00 ₽",300000,₽
27,28,09.10.1990,Java Developer,Java,Москва,"170 000,00 ₽",170000,₽
28,29,17.04.1992,Разработчик информационных систем,.NET,Москва,"190 000,00 ₽",190000,₽
29,30,12.11.1990,Big Data Developer,Big Data,Санкт-Петербург,"185 000,00 ₽",185000,₽
30,31,09.02.1992,Senior Java developer,Java,Санкт-Петербург,"264 367,82 ₽",264368,₽
31,32,19.12.1983,Game Designer,GameDev,Минск,"$1 800,00",124419.419999999998254,USD
32,33,26.09.1981,Java Developer,Java,Москва,"210 000,00 ₽",210000,₽
33,34,03.04.1994,iOS Developer,iOS,Санкт-Петербург,"184 000,00 ₽",184000,₽
34,35,23.12.1988,iOS Developer,iOS,Санкт-Петербург,"170 000,00 ₽",170000,₽
35,36,28.08.1977,BI Dev,BI,Санкт-Петербург,"161 000,00 ₽",161000,₽
36,37,04.05.1988,PHP Dev,PHP,Москва,"201 149,43 ₽",201149,₽
37,38,03.04.1990,JavaScript Engineer,JavaScript,Краков; Польша,"13 000,00 zł",228519.199999999982538,PLN
38,39,10.06.1988,Senior Software Engineer,Java,София; Болгария,"lev6 446,00",259061.517000000021653,BGN
39,40,17.02.1992,Test Automation Engineer,QA,Будапешт; Венгрия,"Ft650 000,00",14835210.000000000000000,HUF
40,41,27.05.1986,Специалист по продаже консалтинговых услуг,Sales,Москва,"150 000,00 ₽",150000,₽
41,42,10.10.1989,ASP.NET Developer,.NET,Санкт-Петербург,"165 000,00 ₽",165000,₽
42,43,26.07.1989,С++ Developer,C++,Москва,"206 896,00 ₽",206896,₽
43,44,04.01.1996,Software Developer,GameDev,Санкт-Петербург,"130 631,00 ₽",130631,₽
44,45,25.01.1978,С++ Developer,C++,Нижний Новгород,"100 000,00 ₽",100000,₽
45,46,25.10.1985,Senior Java developer,Java,Санкт-Петербург,"252 900,00 ₽",252900,₽
46,47,01.06.1979,Solution Architect,OpenStack,Минск,6000 $,414731.399999999965075,USD
47,48,06.03.1989,JS Dev,JS,Санкт-Петербург,"200 000,00 ₽",200000,₽
48,49,04.07.1992,PHP Dev,PHP,Москва,"169 540,23 ₽",169540,₽
49,50,09.02.1985,Java Developer,Java,Москва,"300 000,00 ₽",300000,₽
50,51,04.08.1987,ASP.NET Dev,.NET,Москва,"180 000,00 ₽",180000,₽
51,52,26.12.1987,Senior Java Developer,Java,Санкт-Петербург,"210 000,00 ₽",210000,₽
52,53,07.02.1993,Android-разработчик,Android,Санкт-Петербург,"183 908,00 ₽",183908,₽
53,54,20.06.1991,Разработчик информационных систем,.NET,Москва,"150 000,00 ₽",150000,₽
54,55,04.11.1985,.NET Engineer,.NET,Чехия; Прага,"80 000,00 Kč",2359408.000000000000000,CZK
55,56,08.01.1976,С++ Developer,С++,Атлон; Ирландия,"€ 3 212,00",252214.269999999989523,EUR
56,57,12.09.1986,Java Dev,Java,Атлон; Ирландия,"€ 4 000,00",314090.000000000000000,EUR
57,58,15.04.1989,JS Dev,JS,Атлон; Ирландия,"€ 2 980,00",233997.049999999988358,EUR